name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: '14567332449'
        required: true
        type: string

permissions:
  contents: read
  actions: read  # This is crucial for downloading artifacts

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    steps:
      # Create a directory for the artifacts
      - name: Create dist directory
        run: mkdir -p dist

      # Download artifacts using the specified run ID
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: Build wheels
          run_id: ${{ inputs.run_id }}
          path: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Debug to see what we've got
      - name: List downloaded files
        run: ls -la dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}