on:
  workflow_run:
    workflows: ["Build wheels"]      # Name of your build workflow 
    types: [completed]

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          # pull from the build workflow’s run
          run-id: ${{ github.event.workflow_run.id }}
          path: dist/
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
